_target_: lightning.pytorch.loggers.WandbLogger
project: ${project_name}
name: ${experiment_name}
save_dir: ${paths.output_dir}
offline: False
log_model: False   # 是否将ckpt传到云端，False可节省云端空间
group: "11111"