defaults:
  - _self_
  - mode: train
  - datamodule: cpath/dummy
  - model: cpath/dummy
  - callbacks: default
  - logger: mlflow
  - trainer: default
  - paths: default
  - hydra: default
  - hpo: null


# 顶层全局变量
project_name: deeplab
experiment_name: null
run_name: null

seed: 42 # seed for random number generators in pytorch, numpy and python.random

monitor: val/loss  # for checkpoint callback use
test_after_train: False
resume_ckpt: null


