defaults:
  - _self_
  - mode: train
  - artifacts: default
  - split: default
  - workflow: default
  - datamodule: cpath/dummy
  - model: cpath/dummy
  - callbacks: default
  - logger: mlflow
  - trainer: default
  - paths: default
  - hydra: default
  - hpo: null

project_name: deeplab
experiment_name: null
run_name: null

seed: 42
monitor: val/loss
test_after_train: false
resume_ckpt: null
