_target_: src.models.cpath.transmil.TransMIL
_recursive_: false

init_args:
  model_cfg:
    model_name: transmil
    embed_dim: 2048
    num_classes: 2
    drop_rate: 0.0
  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-4
    weight_decay: 1e-4
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: ${trainer.init_args.max_epochs}
    eta_min: 1e-6