_target_: lightning.pytorch.trainer.Trainer
_recursive_: true

init_args:
  accelerator: gpu
  devices: [0]
  max_epochs: 200
  enable_progress_bar: true
  log_every_n_steps: 20
  num_sanity_val_steps: 0
  default_root_dir: ${paths.output_dir}
