_target_: src.datamodules.tabular_dm.TabularClassificationDataModule
_recursive_: false

init_args:
  data_cfg:
    dataset_name: tabular_dataset
    data_file: data/tabular/manifest.csv # must
    batch_size: 32
    num_workers: 0

    sample_id_column: sample_id
    label_column: label
    group_column: group
    path_column: null
    feature_columns: [f0, f1, f2, f3]

